// Mocks generated by Mockito 5.4.4 from annotations
// in cat_app/test/unit/breed_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cat_app/features/breed/data/apis/breed_api_service.dart' as _i3;
import 'package:cat_app/features/breed/data/models/response/breed_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBreedResponse_0 extends _i1.SmartFake implements _i2.BreedResponse {
  _FakeBreedResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BreedApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBreedApiService extends _i1.Mock implements _i3.BreedApiService {
  MockBreedApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.BreedResponse>> getBreeds({
    int? limit,
    int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBreeds,
          [],
          {
            #limit: limit,
            #page: page,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.BreedResponse>>.value(<_i2.BreedResponse>[]),
      ) as _i4.Future<List<_i2.BreedResponse>>);

  @override
  _i4.Future<_i2.BreedResponse> getBreedById(String? breedId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBreedById,
          [breedId],
        ),
        returnValue: _i4.Future<_i2.BreedResponse>.value(_FakeBreedResponse_0(
          this,
          Invocation.method(
            #getBreedById,
            [breedId],
          ),
        )),
      ) as _i4.Future<_i2.BreedResponse>);

  @override
  _i4.Future<List<_i2.BreedResponse>> searchBreeds({
    required String? query,
    int? attachImage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchBreeds,
          [],
          {
            #query: query,
            #attachImage: attachImage,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.BreedResponse>>.value(<_i2.BreedResponse>[]),
      ) as _i4.Future<List<_i2.BreedResponse>>);
}
